### ISSUE TITLE
ControlPanel: Public Data

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#130]
Stagename:
- Validation parameters where they are coming from? How to manage it?
- Error messages where they are coming from? Are they multilang? How to manage it? How to use the same I use serverside?
- Serverside error are ignored
- check on input?

Profile url:
- min and max length not working
- Validation parameters where they are coming from? How to manage it?
- Serverside error are ignored
- check on input?

About:
- Why *?
- max length?
- Serverside error are ignored

SOCIALS:
- Sort

ADDRESS:
- Sort
- on remove strange message
- search selection not visible
- geometry MISSING

GENERAL
- if error nothing happen (no target, no messages)
- if error serverside success prompt
- if success prompt can disappear after a while?

**Comment by danielesalvatore** [comment]
**Every section: Validation parameters where they are coming from? How to manage it?**

As any other section, the validation function and parameters are defined in the `validate.js` file you can find in the folder correspondent to the section you refer to (e.g. for the Profile > Public section, go to `src/app/redux/components/profile/public/validate.js`.

**Every section: Serverside error are ignored**

I just fixed for all the `Profile` section the rendering of the server side errors: given that for this section we don't use a specific `id` to load the info of the authenticated user, i switched the `getErrorMessage()` methods to be `getDefaultModelErrorMessage()`. This is because the first method expected an `id` to select the correspondent model, the second on get the error message of the first loaded model.

**Every section: Error messages where they are coming from? Are they multilang...**

As any other label in the UI they are multi-language and they have to be handled as any other multi-lang string in the application. (Define the translations, extract the messages, etc.). In the `validate.js` function is where a specific error message is set for a specific validation function. 

**Stagename > check on input?**
We validate that its length must be between 3 and 50 chars (this imply that the parameter is required).

**Profile url > check on input?**
Fixed: We now validate that its length must be between 3 and 50 chars (this imply that the parameter is required).

**About > Why * ?**
To show that the specific tab has a validation error. This is because if a tab has a validation error, its error message is not shown unless the tab is selected. Having this, the user can see that the tab has "something to wrong". Should we keep it?

**About > max length?**
Currently, every text can be max 5000 chars. The value can be changed within the `validate.js` file.

**Address > on remove strange message**

What do you mean?
<img width="528" alt="screen shot 2018-09-22 at 10 52 27" src="https://user-images.githubusercontent.com/6150475/45915480-a7b5b080-be55-11e8-99b0-22ceaf3be468.png">

**Address > search selection not visible**

What do you mean? the input is the search itself
<img width="849" alt="screen shot 2018-09-22 at 10 53 40" src="https://user-images.githubusercontent.com/6150475/45915487-d764b880-be55-11e8-935e-9ea69fb60f42.png">

**Generals > all the issue**
I don't understand what you mean

**Comment by gianlucadelgobbo** [comment]
**Every section: Validation parameters where they are coming from? How to manage it?**

Is better that we use the config.json where there is everything?
```src/app/redux/components/profile/public/validate.js``` can load value from that file?

GENERAL

if there is a client side error on save nothing happen (no target, no messages)

Success prompt can disappear after a while?
