### ISSUE TITLE
ControlPanel: User Emails

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#137]
/admin/profile/emails
/admin/api/profile/emails

Main label as in the menu
Field labels as in config/default.json

is_confirmed missing
if is_confirmed false show button "verify" api ready /admin/api/profile/emails/verify/:email
if is_confirmed true you see the flags

On add show email field only

Server side errors are ignored es: Email in use on new add

**Comment by danielesalvatore** [comment]
@gianlucadelgobbo 
- Added the email verify button for not verified emails
- Additional information for email are now shown on already stored emails: if user add new email, only the input text field is show
- is_confirmed now is visibile

What do you mean with "if is_confirmed true you see the flags"? What the flags are?
Server side is doesn't seems to work on "dev" branch. Cannot get Email already in use error.

**Comment by gianlucadelgobbo** [comment]
To get the error try to add this email:
```
#mongo
> db use avnode;
> db.users.findOne({},{email:1});
```

the flags are all the checkboxes
![emaileditlayout](https://user-images.githubusercontent.com/1591802/45878326-ec334480-bda0-11e8-964c-399aeebd9cd0.jpg)

**Comment by danielesalvatore** [comment]
@gianlucadelgobbo Have a look at the server response I get, because it seems to me to be consistent with the UI

<img width="1440" alt="screen shot 2018-09-22 at 10 31 19" src="https://user-images.githubusercontent.com/6150475/45915269-aa62d680-be52-11e8-8ba6-dff98667aff0.png">

**Comment by danielesalvatore** [comment]
I also implemented the requested behaviour for the three states of the email:
- just added (after the click on the + button) and not stored on db
- stored on server but not verified yet
- verified (subscriptions are not visible)

<img width="991" alt="screen shot 2018-09-22 at 11 48 55" src="https://user-images.githubusercontent.com/6150475/45915930-dc2d6a80-be5d-11e8-976b-46ecf3dcac0f.png">

**Comment by gianlucadelgobbo** [comment]
mail exists error ignored
![screen shot 2018-10-01 at 17 22 55](https://user-images.githubusercontent.com/1591802/46298230-d55dd080-c59e-11e8-8cb4-265c8f7751ce.png)

Can we keep the input box only on add?

Subscriptions flag on full row (under subscriptions)

**Comment by piero80** [comment]
Ciao @gianlucadelgobbo , 
we just implemented the following:
- the input box is only shown on the + add button (once you refresh the page you don't see any empty input text)
- the submissions are now displayed as a full row

Please find below an image of all the possible combination of email and statuses.

<img width="970" alt="screen shot 2018-10-10 at 19 00 08" src="https://user-images.githubusercontent.com/1591103/46753068-19e41d00-ccbf-11e8-9fc3-87e929ceebce.png">

Regarding the validation error on email duplicate, it seems that the check is not performed server side: if we try to submit the form you see in the picture the server reply with a 200 OK. We think it's convenient to have the check server-side because potentially the API can be consumed even by other clients then our UI, so it is safer to have the check on server-side.

**Comment by gianlucadelgobbo** [comment]
@piero80 si è rotto?

**Comment by gianlucadelgobbo** [comment]
LAST BUGS:
is_primary is RADIO 

ADD NEW
Missing the check IF EXISTS on key insert (as slug)
`GET /admin/api/profile/emails/email/:email`
ex:
`GET /admin/api/profile/emails/email/g.delgobbo@flyer.it`

add duplicate all the emails (try with more than one)

ON LOAD
js errors in console when email is more than one
