### ISSUE TITLE
ControlPanel: User Private data

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#139]
Birthday:
- Not saved (wrong var name?)
- Date picker is not good here... try to put 9/10/1970

Validation parameters where they are coming from? How to manage it?

**Comment by danielesalvatore** [comment]
Is should be fixed now on `dev` branch.
The issue was related to the fact that the moment.js obj was directly sent within the request, instead of format is as a string.

Every form contains its own validation function, that you can find in the same folder of the form itself. In this case `profile/private/validation.js` for the sync validation and `profile/private/asyncValidation.js` for the async ones.
