### ISSUE TITLE
API

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#25]
We need more information

**Comment by gianlucadelgobbo** [comment]
Now we need the full object for every event, like this
https://flxer.net/api/lpm-team/events/lpm-2016-amsterdam/
for 
https://flxer.net/lpm-team/events/lpm-2016-amsterdam/

basically is the object of the freezed version

**Comment by gianlucadelgobbo** [comment]
@gianlucadelgobbodo we need authentication for security?the id is a kind of slug of the event? "lpm-2016-amsterdam"
--
authentication for security not now, maybe a way to fragment the event on requests as 
https://flxer.net/api/lpm-team/events/lpm-2016-amsterdam/artists/
https://flxer.net/api/lpm-team/events/lpm-2016-amsterdam/programme/
instead of send the full data, but not in this first step

lpm-2016-amsterdam is the slug

In the new website from zimmer7 there is a different architecture for the objects:

is not
https://flxer.net/lpm-team/events/lpm-2016-amsterdam/
https://flxer.net/USER/TYPEOFCONTENT/SLUG/

BUT

https://flxer.net/events/lpm-2016-amsterdam/
https://flxer.net/TYPEOFCONTENT/SLUG/

MUCH BETTER
